_target_: src.trainers.huggingface_trainer.HuggingFace_Trainer

# gpus: 0

# min_epochs: 1
# max_epochs: 10
output_dir: https://huggingface.co/spaces/dolmalin/hand2text
# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
# resume_from_checkpoint: null
