defaults:
  - ckpt.yaml

model_checkpoint:
  monitor: "val/loss" # name of the logged metric which determines when model is improving
  mode: "min" # "max" means higher metric value is better, can be also "min"

early_stopping:
  monitor: "val/loss" # name of the logged metric which determines when model is improving
  mode: "min" # "max" means higher metric value is better, can be also "min"
