# @package _global_

# overfits to 3 batches

defaults:
  - default.yaml

# trainer:
  # max_epochs: 50
  # overfit_batches: 1

callbacks:
  model_checkpoint:
    monitor: train/loss
  early_stopping:
    monitor: train/loss

model:
  weight_decay: 0
  # net:
  #   dropout: 0

print_config: True
