_target_: src.models.components.baseline.BaseSquareNet.BaseSquareNet

# # corpus: ${hydra:runtime.cwd}/data/How2Sign/vocabulary
# corpus: ${hydra:runtime.cwd}/data/H2T/wlasl_words
batch_size: 2
seq_size: 2
nb_classes: 1999
h_in: 151296
