_target_: src.models.components.vit_cnn.ViTCNNModel
width: 1280
height: 720
channels: 3
kernel_size: 5
corpus: ${hydra:runtime.cwd}/data/How2Sign/vocabulary
do_resize: True
do_normalize: True
image_mean: None
image_std: None
